import 'package:original_dict_app/repository/card_repository.dart';
import 'package:original_dict_app/models/card_entity.dart';


Future<void> insertSampleData() async {
  final List<CardEntity> testCards = [
    CardEntity(
      name: "富士山麓オウムなく",
      nameHira: "ふじさんろくおうむなく",
      intro: "富士山のふもとではオウムの鳴き声も聞こえない。",
      introHira: "ふじさんのふもとではおうむのなきごえもきこえない。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "桜花爛漫",
      nameHira: "おうからんまん",
      intro: "満開の桜が美しく咲き誇るさま。",
      introHira: "まんかいのさくらがうつくしくさいきほこるさま。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "一期一会",
      nameHira: "いちごいちえ",
      intro: "一生に一度の出会いを大切にするという意味。",
      introHira: "いっしょうにいちどのであいをたいせつにするといういみ。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "風林火山",
      nameHira: "ふうりんかざん",
      intro: "武田信玄の軍旗に由来する四字熟語。",
      introHira: "たけだしんげんのぐんきにゆらいするよじじゅくご。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "花鳥風月",
      nameHira: "かちょうふうげつ",
      intro: "自然の美しさや季節の風情を楽しむこと。",
      introHira: "しぜんのうつくしさやきせつのふぜいをたのしむこと。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "温故知新",
      nameHira: "おんこちしん",
      intro: "昔のことを学び、新しい知識を得る。",
      introHira: "むかしのことをまなび、あたらしいちしきをえる。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "以心伝心",
      nameHira: "いしんでんしん",
      intro: "言葉を交わさずとも心が通じ合うこと。",
      introHira: "ことばをかわさずともしんがつうじあうこと。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "天衣無縫",
      nameHira: "てんいむほう",
      intro: "飾り気がなく、自然体であること。",
      introHira: "かざりけがなく、しぜんたいであること。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "灯台下暗し",
      nameHira: "とうだいもとくらし",
      intro: "身近なことほど気づきにくいというたとえ。",
      introHira: "みぢかなことほどきづきにくいというたとえ。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "百花繚乱",
      nameHira: "ひゃっかりょうらん",
      intro: "多くの花が一斉に咲くように、優れた人が並び立つこと。",
      introHira: "おおくのはながいっせいにさくように、すぐれたひとがならびたつこと。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "青天白日",
      nameHira: "せいてんはくじつ",
      intro: "疑いが晴れて堂々と胸を張れること。",
      introHira: "うたがいがはれてどうどうとむねをはれること。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "山紫水明",
      nameHira: "さんしすいめい",
      intro: "山や川が美しく澄んでいる自然の風景。",
      introHira: "やまやかわがうつくしくすんでいるしぜんのふうけい。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "春夏秋冬",
      nameHira: "しゅんかしゅうとう",
      intro: "一年の四つの季節。四季折々の変化。",
      introHira: "いちねんのよっつのきせつ。しきおりおりのへんか。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "雨過天晴",
      nameHira: "うかてんせい",
      intro: "困難を乗り越えて事態が好転すること。",
      introHira: "こんなんをのりこえてじたいがこうてんすること。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "静寂無音",
      nameHira: "せいじゃくむおん",
      intro: "音が全くせず、非常に静まり返っていること。",
      introHira: "おとがまったくせず、ひじょうにしずまりかえっていること。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "光陰矢の如し",
      nameHira: "こういんやのごとし",
      intro: "月日が過ぎるのは非常に早いというたとえ。",
      introHira: "つきひがすぎるのはひじょうにはやいというたとえ。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "紅葉一片",
      nameHira: "こうよういっぺん",
      intro: "一枚のもみじの葉が風に舞う情景。",
      introHira: "いちまいのもみじのはがかぜにまうじょうけい。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "雪月風花",
      nameHira: "せつげつふうか",
      intro: "自然の美しい景物を愛でる風雅な心。",
      introHira: "しぜんのうつくしいけいぶつをめでるふうがなこころ。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "一期一笑",
      nameHira: "いちごいっしょう",
      intro: "出会いの瞬間に笑顔を交わすことの尊さ。",
      introHira: "であいのしゅんかんにえがおをかわすことのとうとさ。",
      isFave: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    CardEntity(
      name: "星河一天",
      nameHira: "せいがいってん",
      intro: "夜空に満天の星が輝くさま。",
      introHira: "よぞらにまんてんのほしがかがやくさま。",
      isFave: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];
  for (final card in testCards) {
    await CardRepository.instance.insertCard(card);
  }
}